import Head from 'next/head'
import { Inter } from 'next/font/google'
import React from 'react'
import router from 'next/router'
import { useAuthContext } from '@/context/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // @ts-ignore
  const { user } = useAuthContext()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 onClick={() => {router.push("/build-resume")}}>Build Resume</h1>
        <h1 onClick={() => {router.push("/my-resumes")}}>View Resume</h1>
        {user && (
          <h2 onClick={() => {router.push("/signout")}}>Sign Out</h2>
        )}
      </main>
    </>
  )
}
